---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/Folder1
  label: Folder1
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/images
public_path: "/static"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.49'
